package com.borislavvucicevic.budgetmate.services;

import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.WorkerThread;

import com.borislavvucicevic.budgetmate.models.Category;
import com.borislavvucicevic.budgetmate.models.Transaction;
import com.borislavvucicevic.budgetmate.models.TransactionPage;
import com.borislavvucicevic.budgetmate.models.UserProfile;
import com.borislavvucicevic.budgetmate.enums.CacheKey;
import com.borislavvucicevic.budgetmate.exceptions.DatabaseException;
import com.borislavvucicevic.budgetmate.schemas.CategorySchema;
import com.borislavvucicevic.budgetmate.schemas.CollectionsSchema;
import com.borislavvucicevic.budgetmate.schemas.TransactionsSchema;
import com.borislavvucicevic.budgetmate.schemas.UserProfileSchema;

import com.google.android.gms.tasks.Tasks;

import com.google.firebase.Timestamp;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;
import com.google.firebase.firestore.QuerySnapshot;
import com.google.firebase.firestore.SetOptions;
import com.google.firebase.firestore.WriteBatch;
import org.jetbrains.annotations.NotNull;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ExecutionException;
import java.util.stream.Collectors;

/**
 * Service responsible for performing database operations with Firebase
 * Cloud Firestore in the BudgetMate application.
 *
 * <p>This service provides methods for creating and retrieving user profiles,
 * retrieving user categories, and creating, retrieving, updating, and deleting
 * financial transactions.</p>
 *
 * <p>Frequently accessed data such as user profiles, categories, and
 * transactions is synchronized with {@link CacheService} to reduce unnecessary
 * Firestore reads and improve application performance.</p>
 *
 * <p>Firestore operations performed by this service use
 * {@code Tasks.await(...)} and therefore execute synchronously. Methods that
 * access Firestore should consequently be called from a background thread
 * rather than the Android UI thread.</p>
 *
 * <p>Failures occurring during Firestore operations are generally wrapped
 * inside {@link DatabaseException}. When an operation is interrupted, the
 * current thread's interrupt status is restored before the exception is
 * propagated.</p>
 *
 * @see FirebaseFirestore
 * @see CacheService
 * @see DatabaseException
 * @see UserProfile
 * @see Transaction
 * @see Category
 */
@WorkerThread
public class DatabaseService {
  /**
   * Log tag used for messages generated by database operations.
   */
  public static final String DATABASE = "DATABASE";

  /**
   * General error message if the caught exception has no message.
   * */
  public static final String UNKNOWN_FIRESTORE_ERROR_OCCURRED = "Unknown Firestore error occurred";

  /**
   * Firestore database instance used to perform all persistent data
   * operations handled by this service.
   */
  private final FirebaseFirestore firestore;

  /**
   * Creates a new database service and initializes its Firestore connection.
   *
   * <p>The service obtains the default {@link FirebaseFirestore} instance,
   * which is subsequently used by all database operations performed by this
   * class.</p>
   */
  public DatabaseService() {
    firestore = FirebaseFirestore.getInstance();
  }

  /**
   * Retrieves the user profile for the specified user ID, prioritizing the local memory cache.
   * <p>
   * This method first checks the {@link CacheService} to see if the profile is already available
   * in memory. If found, it returns the cached instance immediately to eliminate network latency
   * and save Firestore read costs. If it is a cache miss, the method performs a synchronous
   * network call to fetch the live document from Cloud Firestore, maps it to a {@link UserProfile}
   * object, and updates the cache for future requests.
   * </p>
   * <p>
   * @param uid the unique identifier (Firebase Auth UID) of the user whose profile is being requested
   * @return a {@link UserProfile} object containing the user's information
   * @throws DatabaseException if the document does not exist on the server, if the network operation
   *                           fails, or if the thread is interrupted while waiting
   */
  public UserProfile getUserProfile(String uid) throws DatabaseException {
    UserProfile cachedProfile = CacheService.read(CacheKey.USER_PROFILE, UserProfile.class);
    // 1. Return immediately if we already have it in memory
    if (cachedProfile != null) return cachedProfile;

    try {
      DocumentReference documentReference = firestore.collection(CollectionsSchema.USERS).document(uid);

      // Synchronously wait for the document fetch
      DocumentSnapshot snapshot = Tasks.await(documentReference.get());

      if (!snapshot.exists()) {
        throw new DatabaseException("User profile document does not exist on the server.", null);
      }

      // Save to memory cache so the next activity gets it for $0 billing reads
      cachedProfile = snapshot.toObject(UserProfile.class);
      CacheService.store(CacheKey.USER_PROFILE, cachedProfile);
      return cachedProfile;

    }
    catch (ExecutionException exception) {
      throw this.handleException(exception, "User profile read failed: ");
    }
    catch (InterruptedException exception) {
      throw this.handleException(exception, "The user profile read thread was interrupted.");
    }
  }

  /**
   * Creates and stores a new user profile in the Firestore database.
   *
   * <p>The method creates or replaces the user document identified by the
   * supplied user ID inside the {@code users} collection. The user's full name,
   * email address, and home currency are written to Firestore.</p>
   *
   * <p>The database operation is executed synchronously by waiting for the
   * Firestore task to complete. After a successful write, the supplied
   * {@link UserProfile} is also stored in {@link CacheService} under
   * {@link CacheKey#USER_PROFILE}.</p>
   *
   * <p>If the Firestore operation fails with an {@link ExecutionException},
   * the underlying cause is logged and wrapped in a {@link DatabaseException}.
   * If the operation is interrupted, the thread's interrupt status is restored
   * before a {@link DatabaseException} is thrown.</p>
   *
   * @param uid unique identifier of the user whose profile should be created
   * @param userProfile profile information to store in the database and cache
   * @throws DatabaseException if the Firestore write fails or the operation
   *                           is interrupted before completion
   */
  public void createUserProfile(String uid, @NonNull UserProfile userProfile) throws DatabaseException {
    try {
      DocumentReference documentReference = firestore.collection(CollectionsSchema.USERS).document(uid);
      Map<String, Object> user = this.getDocumentMap(userProfile);
      Tasks.await(documentReference.set(user));
      CacheService.store(CacheKey.USER_PROFILE, userProfile);
      Log.d(DATABASE, "Profile creation successfully executed.");
    }
    catch (ExecutionException exception) {
      throw this.handleException(exception, "User profile write failed:");
    }
    catch (InterruptedException exception) {
      throw this.handleException(exception, "The user profile write operation thread was interrupted.");
    }
  }

  /**
   * Deletes all Firestore data belonging to the specified user.
   *
   * <p>The deletion is performed in the following order:</p>
   * <ol>
   *   <li>All transactions belonging to the user are deleted.</li>
   *   <li>All categories belonging to the user are deleted.</li>
   *   <li>The user's profile document is deleted.</li>
   * </ol>
   *
   * <p>The user document is deleted only after the transactions and categories
   * have been successfully removed.</p>
   *
   * <p>This method blocks while waiting for Firestore and must therefore be
   * called from a background thread.</p>
   *
   * @param uid the unique identifier of the user whose data should be deleted
   * @throws DatabaseException if the deletion fails or is interrupted
   */
  public void deleteUserProfile(@NonNull String uid) {
    if (uid.trim().isEmpty()) {
      throw new DatabaseException("User ID cannot be empty.", null);
    }

    try {
      // Deleting transactions collections
      Query transactionQuery = firestore
              .collection(CollectionsSchema.TRANSACTIONS)
              .whereEqualTo(TransactionsSchema.USER_ID, uid);

      QuerySnapshot transactionSnapshot = Tasks.await(transactionQuery.get());

      this.deleteDocuments(transactionSnapshot);

      // Deleting categories
      Query categoryQuery = firestore
              .collection(CollectionsSchema.CATEGORIES)
              .whereEqualTo(TransactionsSchema.USER_ID, uid);

      QuerySnapshot categorySnapshot = Tasks.await(categoryQuery.get());

      this.deleteDocuments(categorySnapshot);

      // Deleting user profile
      DocumentReference userReference = firestore
              .collection(CollectionsSchema.USERS)
              .document(uid);

      Tasks.await(userReference.delete());
    }
    catch (ExecutionException exception) {
      throw this.handleException(exception, "User profile delete operation failed: ");
    }
    catch (InterruptedException exception) {
      throw this.handleException(exception, "The user profile delete operation thread was interrupted.");
    }
  }

  /**
   * Retrieves all custom budget categories belonging to a specific user.
   * Checks the local cache first to minimize database reads, falling back to a
   * synchronous Firestore collection query if the cache is empty.
   *
   * @param uid the unique identifier of the user whose categories are being retrieved.
   * @return a {@link List} of {@link Category} objects matching the user ID.
   * @throws DatabaseException if the network query fails or is interrupted.
   */
  @NonNull
  public List<Category> getCategories(String uid) throws DatabaseException {
    // Return immediately if we already have them in memory
    List<Category> cachedCategories = CacheService.readList(CacheKey.CATEGORIES);
    if (!cachedCategories.isEmpty()) {
      return cachedCategories;
    }

    try {
      Log.d(DATABASE, "Users id (that must not be null): " + uid);
      // Build the query to filter categories by the specific user's ID
      Query query = firestore.collection(CollectionsSchema.CATEGORIES)
              .whereEqualTo(TransactionsSchema.USER_ID, uid);

      // Synchronously wait for the query snapshot fetch
      QuerySnapshot snapshot = Tasks.await(query.get());

      // Map the documents to your Category model class
      List<Category> categoriesList = snapshot.toObjects(Category.class);

      // Save to your cache system so subsequent lookups read from local memory
      CacheService.store(CacheKey.CATEGORIES, categoriesList);

      return categoriesList;

    } catch (ExecutionException exception) {
      throw this.handleException(exception, "Category insertion failed: ");
    } catch (InterruptedException exception) {
      throw this.handleException(exception, "The category insertion thread was interrupted.");
    }
  }

  /**
   * Inserts a new category into the database and stores it in cache.
   *
   * @param category Category object with data about the category document that needs to be added.
   * @return the ID of the newly inserted category
   * @apiNote Called only by {@link #insertTransaction(Transaction)}
   * and {@link #updateTransaction(Transaction)}
   * @see #insertTransaction(Transaction)
   * @see #updateTransaction(Transaction)
   * */
  @NonNull
  private String insertCategory(@NonNull Category category) {
    try {
      DocumentReference newCategoryRef = firestore.collection(CollectionsSchema.CATEGORIES).document();

      category.setID(newCategoryRef.getId());

      Map<String, Object> categoryMap = this.getDocumentMap(category);

      Tasks.await(newCategoryRef.set(categoryMap));

      CacheService.put(CacheKey.CATEGORIES, category);
      Log.d(DATABASE, "Category successfully inserted with generated ID: " + category.getID());

      return category.getID();
    } catch (ExecutionException exception) {
      throw this.handleException(exception, "Transaction fetch failed: ");
    } catch (InterruptedException exception) {
      throw this.handleException(exception, "The transaction fetch operation thread was interrupted.");
    }
  }

  /**
   * Retrieves a page of transactions for the specified user.
   *
   * <p>Transactions are ordered by creation time in descending order. If a
   * pagination cursor is provided, results are loaded after that document.</p>
   *
   * <p>One additional document is requested to determine whether another page
   * is available.</p>
   *
   * @param uid the ID of the user whose transactions should be retrieved
   * @param pageSize the maximum number of transactions to return
   * @param lastVisibleDocument the pagination cursor, or {@code null} for the first page
   * @return a page containing the transactions, pagination cursor, and next-page status
   * @throws IllegalArgumentException if {@code pageSize} is less than or equal to {@code 0}
   * @throws DatabaseException if the Firestore operation fails or is interrupted
   */
  public TransactionPage getTransactions(@NotNull String uid, int pageSize, DocumentSnapshot lastVisibleDocument) throws DatabaseException {
    if (pageSize <= 0) {
      throw new IllegalArgumentException("Page size must be bigger than 0.");
    }

    try {
      Log.d(DATABASE, "Loading user's transactions");

      /*
       * Request one additional document so that we can determine
       * whether another page exists without performing another query.
       */
      long queryLimit = pageSize + 1L;

      // creating a query
      Query query = firestore
              .collection(CollectionsSchema.TRANSACTIONS)
              .whereEqualTo(TransactionsSchema.USER_ID, uid)
              .orderBy(TransactionsSchema.CREATED_ON, Query.Direction.DESCENDING)
              .limit(queryLimit);

      /*
       * A null cursor means that this is the first page.
       */
      if (lastVisibleDocument != null) {
        query = query.startAfter(lastVisibleDocument);
      }

      QuerySnapshot snapshot = Tasks.await(query.get());
      List<DocumentSnapshot> documents = snapshot.getDocuments();
      boolean hasNextPage = documents.size() > pageSize;

      /*
       * The extra document is used only to detect whether another
       * page exists. Do not include it in the returned page.
       */
      int returnedDocumentCount = Math.min(pageSize, documents.size());

      List<Transaction> transactionList = documents
              .stream()
              .map(item -> item.toObject(Transaction.class))
              .filter(Objects::nonNull)
              .collect(Collectors.toList())
              .subList(0, returnedDocumentCount);

      DocumentSnapshot newLastVisibleDocument = returnedDocumentCount > 0 ? documents.get(returnedDocumentCount - 1) : null;
      Log.d(
              DATABASE,
              "Loaded "
                      + transactionList.size()
                      + " transactions. Has next page: "
                      + hasNextPage
      );

      return new TransactionPage(transactionList, newLastVisibleDocument, hasNextPage);
    } catch (ExecutionException exception) {
      throw this.handleException(exception, "Transaction fetch failed: ");
    } catch (InterruptedException exception) {
      throw this.handleException(exception, "The transaction fetch operation thread was interrupted.");
    }
  }

  /**
   * Returns the user's transactions created between two timestamps in descending order.
   *
   * @param uid  the ID of the user who owns the transactions
   * @param from the earliest allowed transaction timestamp
   * @param to   the latest allowed transaction timestamp
   * @return transactions between the supplied timestamps
   * @throws DatabaseException if the query fails or is interrupted
   * @apiNote Both boundaries are inclusive.
   */
  public List<Transaction> getTransactions(@NotNull String uid, @NotNull Timestamp from, @NotNull Timestamp to) throws DatabaseException {
    try {
      Log.d(DATABASE,
              "Loading user's transactions between "
                      + from
                      + " and "
                      + to
      );

      // creating a query
      Query query = firestore
              .collection(CollectionsSchema.TRANSACTIONS)
              .whereEqualTo(TransactionsSchema.USER_ID, uid)
              .whereGreaterThanOrEqualTo(TransactionsSchema.CREATED_ON, from)
              .whereLessThanOrEqualTo(TransactionsSchema.CREATED_ON, to)
              .orderBy(TransactionsSchema.CREATED_ON, Query.Direction.DESCENDING);

      // executing the query
      QuerySnapshot snapshot = Tasks.await(query.get());

      // retrieving documents from the query result
      List<DocumentSnapshot> documents = snapshot.getDocuments();

      // creating a list for transaction objects
      List<Transaction> transactionList = documents
              .stream()
              .map(item -> item.toObject(Transaction.class))
              .filter(Objects::nonNull)
              .collect(Collectors.toList());

      Log.d(DATABASE, "Loaded " + transactionList.size() + " transactions between the supplied dates.");

      return transactionList;
    } catch (ExecutionException exception) {
      throw this.handleException(exception, "Transaction fetch failed: ");
    } catch (InterruptedException exception) {
      throw this.handleException(exception, "The transaction fetch operation thread was interrupted.");
    }
  }
  
  /**
   * Inserts a transaction into Firestore.
   *
   * <p>If the transaction's category does not have an ID, the category is
   * inserted first and its ID is used for the transaction.</p>
   *
   * <p>The generated transaction ID and resolved category ID are assigned to
   * the supplied transaction. After the transaction is successfully written,
   * it is added to the cache.</p>
   *
   * @param transaction the transaction to insert
   * @return the inserted transaction with its assigned IDs
   * @throws DatabaseException if the Firestore operation fails or is interrupted
   */
  public Transaction insertTransaction(@NonNull Transaction transaction) throws DatabaseException {
    try {
      Category category = transaction.getCategory();
      String resolvedCategoryID =
              category.getID() != null ?
              category.getID() :
              this.insertCategory(category);

      // 2. Handle Transaction Logic
      DocumentReference newTransactionRef =
              firestore.collection(CollectionsSchema.TRANSACTIONS).document();

      transaction.setID(newTransactionRef.getId());
      transaction.setCategoryID(resolvedCategoryID);

      Map<String, Object> transactionMap = this.getDocumentMap(transaction);

      Tasks.await(newTransactionRef.set(transactionMap, SetOptions.merge()));
      CacheService.put(CacheKey.TRANSACTIONS, transaction);
      Log.d(DATABASE, "Transaction successfully inserted with ID: " + transaction.getID());
      Log.d(DATABASE, "insertTransaction completed successfully.");

      return transaction;
    } catch (ExecutionException exception) {
      throw this.handleException(exception, "Transaction fetch failed: ");
    } catch (InterruptedException exception) {
      throw this.handleException(exception, "The transaction fetch operation thread was interrupted.");
    }
  }

  /**
   * Updates an existing transaction in Firestore.
   * If the transaction contains a new category without an ID, the category
   * and transaction update are committed together in one batch.
   * This method blocks while waiting for Firestore and must therefore be
   * called from a background thread.
   *
   * @param transaction the transaction containing the updated values
   * @throws DatabaseException if the update fails or is interrupted
   */
  public Transaction updateTransaction(Transaction transaction) throws DatabaseException {
    if (transaction == null) {
      throw new DatabaseException("Transaction cannot be null.", null);
    }

    if (transaction.getID() == null || transaction.getID().trim().isEmpty()) {
      throw new DatabaseException("Transaction ID cannot be null or empty.", null);
    }

    if (transaction.getUserID() == null || transaction.getUserID().trim().isEmpty()) {
      throw new DatabaseException("Transaction user ID cannot be null or empty.", null);
    }

    if(transaction.getCategory() == null) {
      throw new DatabaseException("Transaction must have a category.");
    }

    try {
      // get current category
      Category category = transaction.getCategory();

      // id of already existent or newly created category
      String resolvedCategoryID =
              category.getID() != null ?
                      category.getID() :
                      this.insertCategory(category);

      if (resolvedCategoryID == null || resolvedCategoryID.trim().isEmpty()) {
        throw new DatabaseException("The transaction must have a valid category ID.", null);
      }

      // getting current date and time of the modification
      Timestamp modifiedOn = Timestamp.now();

      // updating the object in memory
      transaction.setCategoryID(resolvedCategoryID);
      transaction.setModifiedOn(modifiedOn);

      // getting transaction's document reference
      DocumentReference transactionReference = firestore
              .collection(CollectionsSchema.TRANSACTIONS)
              .document(transaction.getID());

      // preparing the transaction map for updates
      Map<String, Object> transactionUpdates = this.getDocumentMap(transaction);

      Tasks.await(transactionReference.update(transactionUpdates));

      CacheService.put(CacheKey.TRANSACTIONS, transaction);
      Log.d(DATABASE, "Transaction successfully updated with ID: " + transaction.getID());
      Log.d(DATABASE, "updateTransaction completed successfully.");

      return transaction;
    } catch (ExecutionException exception) {
      throw this.handleException(exception, "Transaction fetch failed: ");
    } catch (InterruptedException exception) {
      throw this.handleException(exception, "The transaction fetch operation thread was interrupted.");
    }
  }

  /**
   * Deletes a transaction from Firestore using its unique document ID.
   * This method blocks while waiting for Firestore, so it must be called
   * from a background thread.
   *
   * @param transactionID the unique Firestore document ID
   * @throws DatabaseException if the deletion fails or is interrupted
   */
  public void deleteTransaction(String transactionID) throws DatabaseException {
    if (transactionID == null || transactionID.trim().isEmpty()) {
      throw new DatabaseException("Transaction ID cannot be null or empty.", null);
    }

    try {
      DocumentReference transactionReference = firestore
              .collection(CollectionsSchema.TRANSACTIONS)
              .document(transactionID);

      // Wait until Firestore confirms that the document was deleted.
      Tasks.await(transactionReference.delete());

      Log.d(DATABASE, "Deleting the transactions with ID: " + transactionID);

      // Update the local cache only after the database operation succeeds.
      CacheService.remove(CacheKey.TRANSACTIONS, transactionID);

      Log.d(DATABASE, "Transaction successfully deleted with ID: " + transactionID);
      Log.d(DATABASE, "deleteTransaction completed successfully.");
    } catch (ExecutionException exception) {
      throw this.handleException(exception, "Transaction fetch failed: ");
    } catch (InterruptedException exception) {
      throw this.handleException(exception, "The transaction fetch operation thread was interrupted.");
    }
  }
  
  /**
   * Deletes all documents contained in the supplied query snapshot.
   *
   * <p>Documents are deleted in batches to avoid creating one excessively
   * large Firestore write batch.</p>
   *
   * @param snapshot query result containing documents that should be deleted
   * @throws ExecutionException if Firestore fails to commit a batch
   * @throws InterruptedException if the current thread is interrupted
   * @apiNote Only called when user is deleting their account.
   * @see #deleteUserProfile(String)
   */
  private void deleteDocuments(@NonNull QuerySnapshot snapshot) throws ExecutionException, InterruptedException {
    final int BATCH_SIZE = 450;
    List<DocumentSnapshot> documents = snapshot.getDocuments();

    for (int start = 0; start < documents.size(); start += BATCH_SIZE) {
      int end = Math.min(start + BATCH_SIZE, documents.size());
      WriteBatch batch = firestore.batch();

      for (int i = start; i < end; i++) {
        batch.delete(documents.get(i).getReference());
      }

      Tasks.await(batch.commit());
    }
  }

  /**
   * Creates a Firestore document map from the specified user profile.
   *
   * @param userProfile the user profile to convert
   * @return a map containing the user profile data
   */
  @NonNull
  private Map<String, Object> getDocumentMap(@NonNull UserProfile userProfile) {
    Map<String, Object> map = new HashMap<>();
    map.put(UserProfileSchema.FULL_NAME, userProfile.getFullName());
    map.put(UserProfileSchema.EMAIL, userProfile.getEmail());
    map.put(UserProfileSchema.HOME_CURRENCY, userProfile.getHomeCurrency());
    return map;
  }

  /**
   * Creates a Firestore document map from the specified category.
   *
   * @param category  the user profile to convert
   * @return a map containing the category data
   */
  @NonNull
  private Map<String, Object> getDocumentMap(@NonNull Category category) {
    Map<String, Object> map = new HashMap<>();
    map.put(CategorySchema.USER_ID, category.getUserID());
    map.put(CategorySchema.NAME, category.getName());
    return map;
  }

  /**
   * Creates a Firestore document map from the specified transaction.
   *
   * @param transaction the user profile to convert
   * @return a map containing the transaction data
   */
  @NonNull
  private Map<String, Object> getDocumentMap(@NonNull Transaction transaction) {
    Map<String, Object> map = new HashMap<>();
    map.put(TransactionsSchema.USER_ID, transaction.getUserID());
    map.put(TransactionsSchema.AMOUNT, transaction.getAmount());
    map.put(TransactionsSchema.CATEGORY_ID, transaction.getCategoryID());
    map.put(TransactionsSchema.TYPE, transaction.getType());
    map.put(TransactionsSchema.CREATED_ON, transaction.getCreatedOn());
    map.put(
            TransactionsSchema.MODIFIED_ON,
            transaction.getModifiedOn() != null
              ? transaction.getModifiedOn()
              : FieldValue.delete()
    );
    map.put(
            TransactionsSchema.NOTES,
            transaction.getNotes() != null
              ? transaction.getNotes()
              : FieldValue.delete()
    );

    return map;
  }

  /**
   * Extracts the root cause from an execution exception, logs the error, and wraps it in a database exception.
   *
   * @param exception The execution exception to extract the cause from.
   * @param message   The contextual log message prefix.
   * @return A new instance of {@link DatabaseException} containing the failure details.
   */
  @NonNull
  private DatabaseException handleException(
          @NonNull ExecutionException exception,
          @NonNull String message
  ) {
    Throwable cause = exception.getCause();
    String errorMessage = (cause != null) ? cause.getMessage() : UNKNOWN_FIRESTORE_ERROR_OCCURRED;
    Log.e(DATABASE, message + errorMessage, cause);
    return new DatabaseException(errorMessage, cause);
  }

  /**
   * Extracts the root cause from an interrupted exception, logs the error, and wraps it in a database exception.
   *
   * @param exception The interrupted exception to extract the cause from.
   * @param message   The contextual log message prefix.
   * @return A new instance of {@link DatabaseException} containing the failure details.
   */
  @NonNull
  private DatabaseException handleException(
          @NonNull InterruptedException exception,
          @NonNull String message
  ) {
    Log.e(DATABASE, message, exception);
    Thread.currentThread().interrupt();
    return new DatabaseException("Database operation was interrupted before completion.", exception);
  }
}