package com.borislavvucicevic.budgetmate.services;

import android.util.Log;

import androidx.annotation.NonNull;

import com.borislavvucicevic.budgetmate.models.Category;
import com.borislavvucicevic.budgetmate.models.Transaction;
import com.borislavvucicevic.budgetmate.models.TransactionPage;
import com.borislavvucicevic.budgetmate.models.UserProfile;
import com.borislavvucicevic.budgetmate.enums.CacheKey;
import com.borislavvucicevic.budgetmate.exceptions.DatabaseException;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.Timestamp;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;
import com.google.firebase.firestore.QuerySnapshot;
import com.google.firebase.firestore.WriteBatch;

import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;

/**
 * Service responsible for performing database operations with Firebase
 * Cloud Firestore in the BudgetMate application.
 *
 * <p>This service provides methods for creating and retrieving user profiles,
 * retrieving user categories, and creating, retrieving, updating, and deleting
 * financial transactions.</p>
 *
 * <p>Frequently accessed data such as user profiles, categories, and
 * transactions is synchronized with {@link CacheService} to reduce unnecessary
 * Firestore reads and improve application performance.</p>
 *
 * <p>Firestore operations performed by this service use
 * {@code Tasks.await(...)} and therefore execute synchronously. Methods that
 * access Firestore should consequently be called from a background thread
 * rather than the Android UI thread.</p>
 *
 * <p>Failures occurring during Firestore operations are generally wrapped
 * inside {@link DatabaseException}. When an operation is interrupted, the
 * current thread's interrupt status is restored before the exception is
 * propagated.</p>
 *
 * @see FirebaseFirestore
 * @see CacheService
 * @see DatabaseException
 * @see UserProfile
 * @see Transaction
 * @see Category
 */
public class DatabaseService {
  /**
   * Log tag used for messages generated by database operations.
   */
  public static final String DATABASE = "DATABASE";

  /**
   * Firestore database instance used to perform all persistent data
   * operations handled by this service.
   */
  private final FirebaseFirestore firestore;

  /**
   * Creates a new database service and initializes its Firestore connection.
   *
   * <p>The service obtains the default {@link FirebaseFirestore} instance,
   * which is subsequently used by all database operations performed by this
   * class.</p>
   */
  public DatabaseService() {
    firestore = FirebaseFirestore.getInstance();
  }

  /**
   * Creates and stores a new user profile in the Firestore database.
   *
   * <p>The method creates or replaces the user document identified by the
   * supplied user ID inside the {@code users} collection. The user's full name,
   * email address, and home currency are written to Firestore.</p>
   *
   * <p>The database operation is executed synchronously by waiting for the
   * Firestore task to complete. After a successful write, the supplied
   * {@link UserProfile} is also stored in {@link CacheService} under
   * {@link CacheKey#USER_PROFILE}.</p>
   *
   * <p>If the Firestore operation fails with an {@link ExecutionException},
   * the underlying cause is logged and wrapped in a {@link DatabaseException}.
   * If the operation is interrupted, the thread's interrupt status is restored
   * before a {@link DatabaseException} is thrown.</p>
   *
   * @param uid unique identifier of the user whose profile should be created
   * @param userProfile profile information to store in the database and cache
   * @throws DatabaseException if the Firestore write fails or the operation
   *                           is interrupted before completion
   */
  public void createUserProfile(String uid, @NonNull UserProfile userProfile) throws DatabaseException {
    try {
      DocumentReference documentReference = firestore.collection("users").document(uid);

      Map<String, Object> user = new HashMap<>();
      user.put("fullName", userProfile.getFullName());
      user.put("email", userProfile.getEmail());
      user.put("homeCurrency", userProfile.getHomeCurrency());

      Tasks.await(documentReference.set(user));
      CacheService.store(CacheKey.USER_PROFILE, userProfile);
      Log.d(DATABASE, "Profile creation successfully executed.");
    } catch (ExecutionException e) {
      Throwable cause = e.getCause();
      String errorMessage = (cause != null) ? cause.getMessage() : "Unknown Firestore error occurred";
      Log.e(DATABASE, "Write failed: " + errorMessage, cause);
      throw new DatabaseException(errorMessage, cause);
    } catch (InterruptedException e) {
      Log.e(DATABASE, "The write operation thread was interrupted.", e);
      Thread.currentThread().interrupt(); // Restore standard thread interrupt flag
      throw new DatabaseException("Database operation was interrupted before completion.", e);
    }
  }

  /**
   * Deletes all Firestore data belonging to the specified user.
   *
   * <p>The deletion is performed in the following order:</p>
   * <ol>
   *   <li>All transactions belonging to the user are deleted.</li>
   *   <li>All categories belonging to the user are deleted.</li>
   *   <li>The user's profile document is deleted.</li>
   * </ol>
   *
   * <p>The user document is deleted only after the transactions and categories
   * have been successfully removed.</p>
   *
   * <p>This method blocks while waiting for Firestore and must therefore be
   * called from a background thread.</p>
   *
   * @param uid the unique identifier of the user whose data should be deleted
   * @throws DatabaseException if the deletion fails or is interrupted
   */
  public void deleteUserProfile(@NonNull String uid) {
    if (uid.trim().isEmpty()) {
      throw new DatabaseException("User ID cannot be empty.", null);
    }

    try {
      // Deleting transactions collections
      Query transactionQuery = firestore
              .collection("transactions")
              .whereEqualTo("userID", uid);

      QuerySnapshot transactionSnapshot = Tasks.await(transactionQuery.get());

      this.deleteDocuments(transactionSnapshot);

      // Deleting categories
      Query categoryQuery = firestore
              .collection("categories")
              .whereEqualTo("userID", uid);

      QuerySnapshot categorySnapshot = Tasks.await(categoryQuery.get());

      this.deleteDocuments(categorySnapshot);

      // Deleting user profile
      DocumentReference userReference = firestore
              .collection("users")
              .document(uid);

      Tasks.await(userReference.delete());
    } catch (ExecutionException exception) {
      Throwable cause = exception.getCause();

      String errorMessage =
              cause != null && cause.getMessage() != null
                      ? cause.getMessage()
                      : "Unknown Firestore user data deletion error occurred.";

      Log.e(
              DATABASE,
              "User data deletion failed: " + errorMessage,
              cause
      );

      throw new DatabaseException(errorMessage, cause);

    } catch (InterruptedException exception) {
      Log.e(
              DATABASE,
              "The user data deletion operation was interrupted.",
              exception
      );

      Thread.currentThread().interrupt();

      throw new DatabaseException(
              "Database operation was interrupted before completion.",
              exception
      );
    }
  }

  /**
   * Retrieves the user profile for the specified user ID, prioritizing the local memory cache.
   * <p>
   * This method first checks the {@link CacheService} to see if the profile is already available
   * in memory. If found, it returns the cached instance immediately to eliminate network latency
   * and save Firestore read costs. If it is a cache miss, the method performs a synchronous
   * network call to fetch the live document from Cloud Firestore, maps it to a {@link UserProfile}
   * object, and updates the cache for future requests.
   * </p>
   * <p>
   * @param uid the unique identifier (Firebase Auth UID) of the user whose profile is being requested
   * @return a {@link UserProfile} object containing the user's information
   * @throws DatabaseException if the document does not exist on the server, if the network operation
   *                           fails, or if the thread is interrupted while waiting
   */
  public UserProfile getUserProfile(String uid) throws DatabaseException {
    UserProfile cachedProfile = CacheService.read(CacheKey.USER_PROFILE, UserProfile.class);
    // 1. Return immediately if we already have it in memory
    if (cachedProfile != null) return cachedProfile;

    try {
      DocumentReference documentReference = firestore.collection("users").document(uid);

      // Synchronously wait for the document fetch
      DocumentSnapshot snapshot = Tasks.await(documentReference.get());

      if (snapshot.exists()) {
        // Save to memory cache so the next activity gets it for $0 billing reads
        cachedProfile = snapshot.toObject(UserProfile.class);
        CacheService.store(CacheKey.USER_PROFILE, cachedProfile);
        return cachedProfile;
      } else {
        throw new DatabaseException("User profile document does not exist on the server.", null);
      }

    } catch (ExecutionException e) {
      Throwable cause = e.getCause();
      String errorMessage = (cause != null) ? cause.getMessage() : "Unknown Firestore error occurred";
      Log.e(DATABASE, "Fetch failed: " + errorMessage, cause);
      throw new DatabaseException(errorMessage, cause);
    } catch (InterruptedException e) {
      Log.e(DATABASE, "The fetch operation thread was interrupted.", e);
      Thread.currentThread().interrupt();
      throw new DatabaseException("Database operation was interrupted before completion.", e);
    }
  }

  /**
   * Retrieves all custom budget categories belonging to a specific user.
   * Checks the local cache first to minimize database reads, falling back to a
   * synchronous Firestore collection query if the cache is empty.
   *
   * @param uid the unique identifier of the user whose categories are being retrieved.
   * @return a {@link List} of {@link Category} objects matching the user ID.
   * @throws DatabaseException if the network query fails or is interrupted.
   */
  public List<Category> getCategories(String uid) throws DatabaseException {
    // Return immediately if we already have them in memory
    List<Category> cachedCategories = CacheService.readList(CacheKey.CATEGORIES);
    if (!cachedCategories.isEmpty()) {
      return cachedCategories;
    }

    try {
      Log.d(DATABASE, "Users id (that must not be null): " + uid);
      // Build the query to filter categories by the specific user's ID
      Query query = firestore.collection("categories")
              .whereEqualTo("userID", uid);

      // Synchronously wait for the query snapshot fetch
      QuerySnapshot snapshot = Tasks.await(query.get());

      // Map the documents to your Category model class
      List<Category> categoriesList = snapshot.toObjects(Category.class);

      // Save to your cache system so subsequent lookups read from local memory
      CacheService.store(CacheKey.CATEGORIES, categoriesList);

      return categoriesList;

    } catch (ExecutionException e) {
      Throwable cause = e.getCause();
      String errorMessage = (cause != null) ? cause.getMessage() : "Unknown Firestore query error occurred";
      Log.e(DATABASE, "Category fetch failed: " + errorMessage, cause);
      throw new DatabaseException(errorMessage, cause);
    } catch (InterruptedException e) {
      Log.e(DATABASE, "The category fetch operation thread was interrupted.", e);
      Thread.currentThread().interrupt();
      throw new DatabaseException("Database operation was interrupted before completion.", e);
    }
  }

  /**
   * Inserts a new transaction into the Firestore database.
   *
   * <p>If the transaction contains a category without an existing ID, a new
   * category document is created first. The generated category ID is assigned
   * to the {@link Category} object and stored in {@link CacheService}.</p>
   *
   * <p>After resolving the category ID, a new transaction document is created
   * in the {@code transactions} collection. The generated transaction ID is
   * assigned to the supplied {@link Transaction}, and the transaction data is
   * written to Firestore. Optional notes are included only when they are not
   * {@code null}.</p>
   *
   * <p>After a successful write, the transaction is stored in
   * {@link CacheService} and the updated {@link Transaction} object is
   * returned.</p>
   *
   * @param transaction the transaction to insert, including its associated category
   * @return the inserted transaction with its generated transaction ID and
   *         resolved category ID
   * @throws DatabaseException if creating the category or transaction fails,
   *                           or if the operation is interrupted
   */
  public Transaction insertTransaction(@NonNull Transaction transaction) throws DatabaseException {
    try {
      Category category = transaction.getCategory();
      String resolvedCategoryID;

      // 1. Handle Category Logic
      if (category.getID() == null) {
        DocumentReference newCategoryRef = firestore.collection("categories").document();
        resolvedCategoryID = newCategoryRef.getId();

        category.setID(resolvedCategoryID);

        Map<String, Object> categoryMap = new HashMap<>();
        categoryMap.put("userID", transaction.getUserID());
        categoryMap.put("name", category.getName());

        Tasks.await(newCategoryRef.set(categoryMap));
        CacheService.put(CacheKey.CATEGORIES, category);
        Log.d(DATABASE, "Category successfully inserted with generated ID: " + resolvedCategoryID);
      } else {
        resolvedCategoryID = category.getID();
      }

      // 2. Handle Transaction Logic
      DocumentReference newTransactionRef = firestore.collection("transactions").document();
      transaction.setID(newTransactionRef.getId());
      transaction.setCategoryID(resolvedCategoryID);

      Map<String, Object> transactionMap = new HashMap<>();
      transactionMap.put("userID", transaction.getUserID());
      transactionMap.put("amount", transaction.getAmount());
      transactionMap.put("categoryID", resolvedCategoryID);
      transactionMap.put("createdOn", transaction.getCreatedOn());
      transactionMap.put("type", transaction.getType());

      // Conditionally add optional fields to avoid inserting null values into Firestore
      if (transaction.getNotes() != null) {
        transactionMap.put("notes", transaction.getNotes());
      }

      Tasks.await(newTransactionRef.set(transactionMap));
      CacheService.put(CacheKey.TRANSACTIONS, transaction);
      Log.d(DATABASE, "Transaction successfully inserted with ID: " + transaction.getID());
      Log.d(DATABASE, "insertTransaction completed successfully.");

      return transaction;
    } catch (ExecutionException e) {
      Throwable cause = e.getCause();
      String errorMessage = (cause != null) ? cause.getMessage() : "Unknown Firestore error occurred";
      Log.e(DATABASE, "Transaction insertion failed: " + errorMessage, cause);
      throw new DatabaseException(errorMessage, cause);
    } catch (InterruptedException e) {
      Log.e(DATABASE, "The transaction write operation thread was interrupted.", e);
      Thread.currentThread().interrupt();
      throw new DatabaseException("Database operation was interrupted before completion.", e);
    }
  }

  /**
   * Retrieves a paginated collection of transactions belonging to the specified user.
   *
   * <p>The method queries the Firestore {@code transactions} collection for documents
   * whose {@code userID} matches the supplied user identifier. Results are ordered by
   * {@code createdOn} in descending order so that the most recent transactions are
   * returned first.</p>
   *
   * <p>To determine whether another page of results exists, the query requests one
   * additional document beyond the requested page size. This extra document is used
   * only for pagination detection and is not included in the returned transaction list.</p>
   *
   * <p>If {@code lastVisibleDocument} is not {@code null}, it is used as the pagination
   * cursor and the query continues after that document. A {@code null} cursor indicates
   * that the first page should be loaded.</p>
   *
   * <p>Each returned Firestore document is converted into a {@link Transaction}. The
   * resulting transactions, the new pagination cursor, and the flag indicating whether
   * another page exists are returned inside a {@link TransactionPage}.</p>
   *
   * @param uid unique identifier of the user whose transactions should be retrieved
   * @param pageSize maximum number of transactions to include in the returned page;
   *                 must be greater than {@code 0}
   * @param lastVisibleDocument Firestore document used as the pagination cursor,
   *                            or {@code null} when retrieving the first page
   * @return a {@link TransactionPage} containing the retrieved transactions,
   *         the new pagination cursor, and information about whether another page exists
   * @throws IllegalArgumentException if {@code pageSize} is less than or equal to {@code 0}
   * @throws DatabaseException if the Firestore query fails or the operation is interrupted
   */
  public TransactionPage getTransactions(@NotNull String uid, int pageSize, DocumentSnapshot lastVisibleDocument) throws DatabaseException {
    if (pageSize <= 0) {
      throw new IllegalArgumentException("Page size must be bigger than 0.");
    }

    try {
      Log.d(DATABASE, "Loading user's transactions");
      /*
       * Request one additional document so that we can determine
       * whether another page exists without performing another query.
       */
      long queryLimit = (long) pageSize + 1L;

      // creating a query
      Query query = firestore
              .collection("transactions")
              .whereEqualTo("userID", uid)
              .orderBy("createdOn", Query.Direction.DESCENDING)
              .limit(queryLimit);

      /*
       * A null cursor means that this is the first page.
       */
      if (lastVisibleDocument != null) {
        query = query.startAfter(lastVisibleDocument);
      }

      QuerySnapshot snapshot = Tasks.await(query.get());
      List<DocumentSnapshot> documents = snapshot.getDocuments();
      boolean hasNextPage = documents.size() > pageSize;

      /*
       * The extra document is used only to detect whether another
       * page exists. Do not include it in the returned page.
       */
      int returnedDocumentCount =
              Math.min(pageSize, documents.size());

      List<Transaction> transactionList = new ArrayList<>(returnedDocumentCount);

      for(int i = 0; i < returnedDocumentCount; i++) {
        DocumentSnapshot document = documents.get(i);
        Transaction transaction = document.toObject(Transaction.class);

        if(transaction != null) {
          transactionList.add(transaction);
        } else {
          Log.w(DATABASE, "Could not convert document snapshot to object. ID:  " + document.getId());
        }
      }

      DocumentSnapshot newLastVisibleDocument = returnedDocumentCount > 0 ? documents.get(returnedDocumentCount - 1) : null;
      Log.d(
              DATABASE,
              "Loaded "
                      + transactionList.size()
                      + " transactions. Has next page: "
                      + hasNextPage
      );

      return new TransactionPage(transactionList, newLastVisibleDocument, hasNextPage);
    } catch (ExecutionException e) {
      Throwable cause = e.getCause();

      String errorMessage =
              cause != null && cause.getMessage() != null
                      ? cause.getMessage()
                      : "Unknown Firestore transaction query error occurred.";

      Log.e(DATABASE, "Transaction fetch failed: " + errorMessage, cause);

      throw new DatabaseException(errorMessage, cause);
    } catch (InterruptedException e) {
      Log.e(DATABASE, "The transaction fetch operation was interrupted.", e);

      Thread.currentThread().interrupt();

      throw new DatabaseException("Database operation was interrupted before completion.", e);
    }
  }

  /**
   * Returns the user's transactions created between two timestamps,
   * ordered from newest to oldest.
   *
   * Both date boundaries are inclusive:
   *
   * createdOn >= from
   * createdOn <= to
   *
   * This method blocks while waiting for Firestore, so it must be
   * called from a background thread.
   *
   * @param uid  the ID of the user who owns the transactions
   * @param from the earliest allowed transaction timestamp
   * @param to   the latest allowed transaction timestamp
   * @return transactions between the supplied timestamps
   * @throws DatabaseException if the query fails or is interrupted
   */
  public List<Transaction> getTransactions(@NotNull String uid, @NotNull Timestamp from, @NotNull Timestamp to) throws DatabaseException {

    if (uid.trim().isEmpty()) {
      throw new IllegalArgumentException("User ID cannot be empty.");
    }

    if (from.compareTo(to) > 0) {
      throw new IllegalArgumentException("'from' timestamp cannot be later than the 'to' timestamp.");
    }

    try {
      Log.d(
              DATABASE,
              "Loading user's transactions between "
                      + from
                      + " and "
                      + to
      );

      // creating a query
      Query query = firestore
              .collection("transactions")
              .whereEqualTo("userID", uid)
              .whereGreaterThanOrEqualTo("createdOn", from)
              .whereLessThanOrEqualTo("createdOn", to)
              .orderBy("createdOn", Query.Direction.DESCENDING);

      // executing the query
      QuerySnapshot snapshot = Tasks.await(query.get());

      // retrieving documents from the query result
      List<DocumentSnapshot> documents = snapshot.getDocuments();

      // creating a list for transaction objects
      List<Transaction> transactionList = new ArrayList<>(documents.size());

      // converting documents to transaction objects
      for (DocumentSnapshot document : documents) {
        Transaction transaction = document.toObject(Transaction.class);

        if (transaction != null) {
          transactionList.add(transaction);
        } else {
          Log.w(DATABASE, "Could not convert transaction document. ID: " + document.getId());
        }
      }

      Log.d(DATABASE, "Loaded " + transactionList.size() + " transactions between the supplied dates.");

      return transactionList;

    } catch (ExecutionException exception) {
      Throwable cause = exception.getCause();

      String errorMessage =
              cause != null && cause.getMessage() != null
                      ? cause.getMessage()
                      : "Unknown Firestore transaction query error occurred.";

      Log.e(
              DATABASE,
              "Transaction date-range query failed: "
                      + errorMessage,
              cause
      );

      throw new DatabaseException(
              errorMessage,
              cause
      );

    } catch (InterruptedException exception) {
      Log.e(
              DATABASE,
              "The transaction date-range query was interrupted.",
              exception
      );

      Thread.currentThread().interrupt();

      throw new DatabaseException(
              "Database operation was interrupted before completion.",
              exception
      );
    }
  }

  /**
   * Deletes a transaction from Firestore using its unique document ID.
   * This method blocks while waiting for Firestore, so it must be called
   * from a background thread.
   *
   * @param transactionID the unique Firestore document ID
   * @throws DatabaseException if the deletion fails or is interrupted
   */
  public void deleteTransaction(String transactionID) throws DatabaseException {
    if (transactionID == null || transactionID.trim().isEmpty()) {
      throw new DatabaseException("Transaction ID cannot be null or empty.", null);
    }

    try {
      DocumentReference transactionReference = firestore
              .collection("transactions")
              .document(transactionID);

      // Wait until Firestore confirms that the document was deleted.
      Tasks.await(transactionReference.delete());

      // Update the local cache only after the database operation succeeds.
      CacheService.remove(CacheKey.TRANSACTIONS, transactionID);

      Log.d(DATABASE, "Transaction successfully deleted with ID: " + transactionID);
      Log.d(DATABASE, "deleteTransaction completed successfully.");
    } catch (ExecutionException e) {
      Throwable cause = e.getCause();

      String errorMessage =
              cause != null && cause.getMessage() != null
                      ? cause.getMessage()
                      : "Unknown Firestore deletion error occurred.";

      Log.e(DATABASE, "Transaction deletion failed: " + errorMessage, cause);

      throw new DatabaseException(errorMessage, cause);
    } catch (InterruptedException e) {
      Log.e(DATABASE, "The transaction deletion operation thread was interrupted.", e);

      Thread.currentThread().interrupt();

      throw new DatabaseException("Database operation was interrupted before completion.", e);
    }
  }

  /**
   * Updates an existing transaction in Firestore.
   * If the transaction contains a new category without an ID, the category
   * and transaction update are committed together in one batch.
   * This method blocks while waiting for Firestore and must therefore be
   * called from a background thread.
   *
   * @param transaction the transaction containing the updated values
   * @throws DatabaseException if the update fails or is interrupted
   */
  public Transaction updateTransaction(Transaction transaction) throws DatabaseException {
    if (transaction == null) {
      throw new DatabaseException("Transaction cannot be null.", null);
    }

    if (transaction.getID() == null || transaction.getID().trim().isEmpty()) {
      throw new DatabaseException("Transaction ID cannot be null or empty.", null);
    }

    if (transaction.getUserID() == null || transaction.getUserID().trim().isEmpty()) {
      throw new DatabaseException("Transaction user ID cannot be null or empty.", null);
    }

    try {
      WriteBatch batch = firestore.batch();

      // get current category
      Category category = transaction.getCategory();

      // a holder for a new category if one needs to be created
      Category newlyCreatedCategory = null;

      // id of already existent or newly created category
      String resolvedCategoryID = transaction.getCategoryID();

      /*
       * Resolve the transaction category.
       *
       * When the category has no ID, it is a new category and must
       * be inserted before it can be referenced by the transaction.
       */
      if (category != null) {
        if (category.getID() == null || category.getID().trim().isEmpty()) {

          // creating new category document reference
          DocumentReference newCategoryReference = firestore
                  .collection("categories")
                  .document();

          // retrieving id of the newly created category
          resolvedCategoryID = newCategoryReference.getId();

          category.setID(resolvedCategoryID);

          // preparing new category
          Map<String, Object> categoryMap = new HashMap<>();
          categoryMap.put("userID", transaction.getUserID());
          categoryMap.put("name", category.getName());

          // adding the category map to the batch for execution
          batch.set(newCategoryReference, categoryMap);

          newlyCreatedCategory = category;
        } else {
          resolvedCategoryID = category.getID();
        }
      }

      if (resolvedCategoryID == null || resolvedCategoryID.trim().isEmpty()) {
        throw new DatabaseException("The transaction must have a valid category ID.", null);
      }

      // getting current date and time of the modification
      Timestamp modifiedOn = Timestamp.now();

      // updating the object in memory
      transaction.setCategoryID(resolvedCategoryID);
      transaction.setModifiedOn(modifiedOn);

      // getting transaction's document reference
      DocumentReference transactionReference = firestore
              .collection("transactions")
              .document(transaction.getID());

      // preparing the transaction map for updates
      Map<String, Object> transactionUpdates = new HashMap<>();
      transactionUpdates.put("amount", transaction.getAmount());
      transactionUpdates.put("categoryID", resolvedCategoryID);
      transactionUpdates.put("type", transaction.getType());
      transactionUpdates.put("modifiedOn", modifiedOn);
      transactionUpdates.put("notes", transaction.getNotes() != null ? transaction.getNotes() : FieldValue.delete());

      /*
       * update() fails if the transaction document does not exist,
       * which is preferable to silently creating another document.
       */
      batch.update(
              transactionReference,
              transactionUpdates
      );

      Tasks.await(batch.commit());

      /*
       * Update the cache only after Firestore confirms that the
       * entire batch was committed successfully.
       */
      if (newlyCreatedCategory != null) {
        CacheService.put(CacheKey.CATEGORIES, newlyCreatedCategory);
      }

      CacheService.put(CacheKey.TRANSACTIONS, transaction);

      Log.d(DATABASE, "Transaction successfully updated with ID: " + transaction.getID());
      Log.d(DATABASE, "updateTransaction completed successfully.");

      return transaction;
    } catch (ExecutionException exception) {
      Throwable cause = exception.getCause();

      String errorMessage = cause != null && cause.getMessage() != null
                      ? cause.getMessage()
                      : "Unknown Firestore update error occurred.";

      Log.e(DATABASE, "Transaction update failed: " + errorMessage, cause);

      throw new DatabaseException(errorMessage, cause);

    } catch (InterruptedException exception) {
      Log.e(DATABASE, "The transaction update operation thread was interrupted.", exception);
      Thread.currentThread().interrupt();
      throw new DatabaseException("Database operation was interrupted before completion.", exception);
    }
  }
  /**
   * Deletes all documents contained in the supplied query snapshot.
   *
   * <p>Documents are deleted in batches to avoid creating one excessively
   * large Firestore write batch.</p>
   *
   * @param snapshot query result containing documents that should be deleted
   * @throws ExecutionException if Firestore fails to commit a batch
   * @throws InterruptedException if the current thread is interrupted
   */
  private void deleteDocuments(@NonNull QuerySnapshot snapshot) throws ExecutionException, InterruptedException {
    final int BATCH_SIZE = 450;
    List<DocumentSnapshot> documents = snapshot.getDocuments();

    for (int start = 0; start < documents.size(); start += BATCH_SIZE) {
      int end = Math.min(start + BATCH_SIZE, documents.size());
      WriteBatch batch = firestore.batch();

      for (int i = start; i < end; i++) {
        batch.delete(documents.get(i).getReference());
      }

      Tasks.await(batch.commit());
    }
  }
}